from __future__ import annotations

# Real, curated national/private/corporate funding sources provided by the team
# as active as of May 2026. These are NOT dummy/fake grants. They are stored as
# national opportunities and shown for any U.S. state when the user's need fits.
# Users are still told to verify final rules/deadlines on official websites.
CURATED_VERIFIED_GRANTS: list[dict] = [
    {
        "source": "WomensNet",
        "source_id": "womensnet-amber-grant-2026",
        "title": "Amber Grant",
        "description": "Monthly grant program for women entrepreneurs and women-owned businesses. Suitable for small businesses, salons, boutiques, service businesses, startups, creators, and local business growth needs including equipment, marketing, inventory, and expansion.",
        "eligibility": "Women entrepreneurs and women-owned businesses. Final eligibility, rules, and deadlines must be verified on the official Amber Grant website.",
        "audience": "organization",
        "category": "business",
        "amount_min": 10000,
        "amount_max": 25000,
        "deadline": "Monthly rolling; year-end award available",
        "state": "National",
        "application_url": "https://ambergrantsforwomen.com",
        "verified": True,
        "confidence_score": 94,
        "raw_json": {
            "status": "Active",
            "curated_as_of": "May 2026",
            "funding_type": "private",
            "source_kind": "private_grant",
            "industries": ["beauty", "salon", "spa", "cosmetology", "barber", "retail", "service_business", "creative", "local_business", "small_business"],
            "needs_supported": ["equipment", "expansion", "startup capital", "marketing", "inventory", "working capital", "business growth"],
            "demographics": ["women", "women_owned"],
            "organization_types": ["business", "startup", "small_business"],
            "states": ["National"],
            "amount_display": "$10,000 monthly + $25,000 year-end",
        },
    },
    {
        "source": "IFundWomen",
        "source_id": "ifundwomen-universal-grants-2026",
        "title": "IFundWomen Grants",
        "description": "Rolling partner grant marketplace and universal application opportunities for women founders and entrepreneurs. Relevant to small businesses, startups, creators, service businesses, beauty salons, retail brands, and growth-stage businesses seeking private or corporate funding.",
        "eligibility": "Women founders and entrepreneurs; eligibility varies by partner grant. Verify current partner programs and deadlines on IFundWomen.",
        "audience": "organization",
        "category": "business",
        "amount_min": 5000,
        "amount_max": 100000,
        "deadline": "Rolling; varies by partner grant",
        "state": "National",
        "application_url": "https://ifundwomen.com",
        "verified": True,
        "confidence_score": 93,
        "raw_json": {
            "status": "Active",
            "curated_as_of": "May 2026",
            "funding_type": "private",
            "source_kind": "private_grant_marketplace",
            "industries": ["beauty", "salon", "wellness", "retail", "technology", "creator", "creative", "service_business", "startup", "small_business"],
            "needs_supported": ["startup capital", "equipment", "marketing", "expansion", "product launch", "working capital", "digital growth"],
            "demographics": ["women", "women_owned", "founders"],
            "organization_types": ["business", "startup", "small_business"],
            "states": ["National"],
            "amount_display": "Varies, commonly $5,000-$100,000+ depending on partner grant",
        },
    },
    {
        "source": "Hello Alice",
        "source_id": "hello-alice-small-business-grants-2026",
        "title": "Hello Alice Grants",
        "description": "Small business grant platform with multiple corporate and partner grant cycles. Relevant for small businesses, startups, local businesses, beauty salons, service providers, minority-owned businesses, women-owned businesses, and growth needs.",
        "eligibility": "Small business owners; eligibility varies by active grant cycle. Verify each cycle on Hello Alice before applying.",
        "audience": "organization",
        "category": "business",
        "amount_min": 5000,
        "amount_max": 50000,
        "deadline": "Rolling; multiple cycles in 2026",
        "state": "National",
        "application_url": "https://helloalice.com",
        "verified": True,
        "confidence_score": 92,
        "raw_json": {
            "status": "Active",
            "curated_as_of": "May 2026",
            "funding_type": "private",
            "source_kind": "corporate_private_grants",
            "industries": ["beauty", "salon", "restaurant", "retail", "service_business", "technology", "consumer", "local_business", "small_business", "startup"],
            "needs_supported": ["equipment", "expansion", "marketing", "digital transformation", "startup capital", "working capital", "business growth"],
            "demographics": ["women_owned", "minority_owned", "small_business"],
            "organization_types": ["business", "startup", "small_business"],
            "states": ["National"],
            "amount_display": "$5,000-$50,000 depending on cycle",
        },
    },
    {
        "source": "FedEx",
        "source_id": "fedex-small-business-grant-contest-2026",
        "title": "FedEx Small Business Grant Contest",
        "description": "National small business grant contest supporting small business growth. Relevant to product, retail, service, beauty, salon, local business, and expansion needs when the business meets the contest rules.",
        "eligibility": "U.S. small businesses meeting FedEx contest rules. Verify open dates, official rules, and eligibility on FedEx.",
        "audience": "organization",
        "category": "business",
        "amount_min": 10000,
        "amount_max": 50000,
        "deadline": "Typically Q2-Q3 cycle; verify current 2026 dates",
        "state": "National",
        "application_url": "https://www.fedex.com/en-us/small-business/grants.html",
        "verified": True,
        "confidence_score": 91,
        "raw_json": {
            "status": "Active",
            "curated_as_of": "May 2026",
            "funding_type": "corporate",
            "source_kind": "contest",
            "industries": ["beauty", "salon", "retail", "product_business", "service_business", "local_business", "small_business"],
            "needs_supported": ["growth", "expansion", "equipment", "marketing", "inventory", "shipping", "working capital"],
            "demographics": ["small_business"],
            "organization_types": ["business", "small_business"],
            "states": ["National"],
            "amount_display": "Up to $50,000",
        },
    },
    {
        "source": "Visa",
        "source_id": "visa-everywhere-initiative-2026",
        "title": "Visa Everywhere Initiative",
        "description": "Global/national innovation competition for startups and founders building commerce, payments, fintech, and business solutions. Relevant primarily to startups, fintech, technology, and innovative small businesses.",
        "eligibility": "Startups and founders that meet current Visa competition rules. Verify active regional cycle and eligibility on Visa.",
        "audience": "organization",
        "category": "startup",
        "amount_min": 10000,
        "amount_max": 50000,
        "deadline": "Rolling/seasonal competitions; verify current 2026 cycle",
        "state": "National",
        "application_url": "https://usa.visa.com",
        "verified": True,
        "confidence_score": 88,
        "raw_json": {
            "status": "Active",
            "curated_as_of": "May 2026",
            "funding_type": "corporate_competition",
            "source_kind": "competition",
            "industries": ["startup", "technology", "fintech", "payments", "commerce", "software", "innovation"],
            "needs_supported": ["startup capital", "growth", "competition", "technology development", "market expansion"],
            "demographics": ["founders", "startups"],
            "organization_types": ["startup", "business"],
            "states": ["National"],
            "amount_display": "$10,000-$50,000+ prizes",
        },
    },
    {
        "source": "MBDA",
        "source_id": "mbda-business-grants-programs-2026",
        "title": "Minority Business Development Agency Business Grants & Programs",
        "description": "MBDA programs and partner opportunities supporting minority business enterprises, business centers, technical assistance, and growth. Relevant to minority-owned small businesses and entrepreneurs across many industries including beauty, salon, service, retail, and local businesses.",
        "eligibility": "Minority business enterprises and eligible partner/program applicants; specific opportunities vary. Verify open opportunities and program rules on MBDA.",
        "audience": "organization",
        "category": "business",
        "amount_min": 10000,
        "amount_max": 250000,
        "deadline": "Rolling/varies by program and partner opportunity",
        "state": "National",
        "application_url": "https://www.mbda.gov",
        "verified": True,
        "confidence_score": 92,
        "raw_json": {
            "status": "Active",
            "curated_as_of": "May 2026",
            "funding_type": "government_program",
            "source_kind": "business_programs",
            "industries": ["beauty", "salon", "retail", "service_business", "local_business", "manufacturing", "technology", "small_business"],
            "needs_supported": ["business growth", "technical assistance", "expansion", "capital readiness", "market access", "training"],
            "demographics": ["minority_owned", "minority_business"],
            "organization_types": ["business", "small_business"],
            "states": ["National"],
            "amount_display": "Varies, often $10,000-$250,000+ through programs/partners",
        },
    },
    {
        "source": "Verizon",
        "source_id": "verizon-small-business-digital-ready-2026",
        "title": "Verizon Small Business Digital Ready Grants",
        "description": "Small business training and grant opportunities supporting digital readiness, marketing, online presence, operations, and business growth. Relevant to salons, beauty businesses, restaurants, retail, service businesses, and local entrepreneurs needing digital tools or growth support.",
        "eligibility": "Small businesses participating in Verizon Small Business Digital Ready; grant drawings and rules vary. Verify current grant details on Verizon Digital Ready.",
        "audience": "organization",
        "category": "business",
        "amount_min": 10000,
        "amount_max": 10000,
        "deadline": "Rolling monthly/periodic grant draws; verify current cycle",
        "state": "National",
        "application_url": "https://digitalready.verizonwireless.com/funding/details",
        "verified": True,
        "confidence_score": 93,
        "raw_json": {
            "status": "Active",
            "curated_as_of": "May 2026",
            "funding_type": "corporate_private",
            "source_kind": "grant_training_program",
            "industries": ["beauty", "salon", "spa", "restaurant", "retail", "service_business", "local_business", "small_business"],
            "needs_supported": ["digital transformation", "marketing", "website", "technology", "equipment", "business growth", "training"],
            "demographics": ["small_business"],
            "organization_types": ["business", "small_business"],
            "states": ["National"],
            "amount_display": "$10,000 grants + training",
        },
    },
    {
        "source": "Cartier Women's Initiative",
        "source_id": "cartier-womens-initiative-2026",
        "title": "Cartier Women's Initiative",
        "description": "Fellowship and awards program for women impact entrepreneurs. Best suited to women-led impact businesses and startups with strong social/environmental mission, scalable model, and founder story.",
        "eligibility": "Women impact entrepreneurs meeting the current Cartier Women's Initiative eligibility criteria. Verify application cycle and rules on the official site.",
        "audience": "organization",
        "category": "startup",
        "amount_min": 30000,
        "amount_max": 100000,
        "deadline": "Annual/seasonal cycle; verify current intake",
        "state": "National",
        "application_url": "https://www.cartierwomensinitiative.com",
        "verified": True,
        "confidence_score": 89,
        "raw_json": {
            "status": "Active",
            "curated_as_of": "May 2026",
            "funding_type": "private_foundation_award",
            "source_kind": "fellowship_award",
            "industries": ["startup", "impact", "social_enterprise", "sustainability", "healthcare", "education", "technology", "consumer", "women_led"],
            "needs_supported": ["growth", "impact scaling", "startup capital", "mentorship", "market expansion"],
            "demographics": ["women", "women_led", "founders"],
            "organization_types": ["startup", "business", "social_enterprise"],
            "states": ["National"],
            "amount_display": "Up to $100,000",
        },
    },
    {
        "source": "NASE",
        "source_id": "nase-growth-grants-2026",
        "title": "NASE Growth Grants",
        "description": "Growth grant program for members of the National Association for the Self-Employed. Relevant to microbusinesses, solo entrepreneurs, service businesses, consultants, beauty/salon professionals, and small business owners needing equipment, marketing, training, or expansion support.",
        "eligibility": "NASE members and eligible self-employed business owners; verify membership rules, deadlines, and current grant requirements on NASE.",
        "audience": "organization",
        "category": "business",
        "amount_min": 4000,
        "amount_max": 4000,
        "deadline": "Quarterly; verify current cycle",
        "state": "National",
        "application_url": "https://www.nase.org",
        "verified": True,
        "confidence_score": 90,
        "raw_json": {
            "status": "Active",
            "curated_as_of": "May 2026",
            "funding_type": "private_membership_grant",
            "source_kind": "growth_grant",
            "industries": ["beauty", "salon", "spa", "consulting", "retail", "service_business", "self_employed", "microbusiness", "small_business"],
            "needs_supported": ["equipment", "marketing", "training", "expansion", "website", "business growth", "supplies"],
            "demographics": ["self_employed", "small_business"],
            "organization_types": ["business", "small_business", "self_employed"],
            "states": ["National"],
            "amount_display": "Up to $4,000",
        },
    },
]

# Additional real verified funding sources for broader business categories.
# These are official source records, not dummy opportunities. Users must verify active cycle/deadline.
ADDITIONAL_UNIVERSAL_FUNDING_SOURCES: list[dict] = [
    {
        "source": "SBIR.gov",
        "source_id": "sbir-sttr-universal-2026",
        "title": "SBIR/STTR Innovation Funding",
        "description": "Federal innovation funding pathway for technology, research, scientific, healthcare, manufacturing, clean energy, and software startups developing commercially promising products or services.",
        "eligibility": "Eligible U.S. small businesses pursuing research and development; agency-specific rules apply. Verify current solicitations on SBIR.gov.",
        "audience": "organization", "category": "startup", "amount_min": 50000, "amount_max": 1500000,
        "deadline": "Varies by federal agency solicitation", "state": "National", "application_url": "https://www.sbir.gov",
        "verified": True, "confidence_score": 94,
        "raw_json": {"status":"Active","funding_type":"federal_innovation","source_kind":"federal_program","industries":["technology","software","ai","healthcare","manufacturing","clean_energy","agriculture","education","innovation"],"needs_supported":["research","development","prototype","commercialization","startup capital","technology development"],"organization_types":["startup","business","small_business"],"states":["National"],"amount_display":"Varies by agency; Phase I/II awards can range from tens of thousands to $1M+"}
    },
    {
        "source": "SBA",
        "source_id": "sba-step-export-2026",
        "title": "SBA State Trade Expansion Program (STEP)",
        "description": "Export growth support for small businesses seeking international sales, trade shows, export marketing, and global expansion. Relevant to product businesses, manufacturers, ecommerce, food brands, beauty brands, and scalable local businesses ready to sell internationally.",
        "eligibility": "Eligible small businesses through participating state STEP programs; rules vary by state. Verify through SBA and the state trade office.",
        "audience": "organization", "category": "business", "amount_min": None, "amount_max": None,
        "deadline": "Varies by state program", "state": "National", "application_url": "https://www.sba.gov/funding-programs/grants/state-trade-expansion-program-step",
        "verified": True, "confidence_score": 94,
        "raw_json": {"status":"Active","funding_type":"government_program","source_kind":"export_program","industries":["retail_ecommerce","manufacturing","food","beauty","technology","agriculture","consumer products","small_business"],"needs_supported":["export growth","market expansion","trade shows","marketing","international sales"],"organization_types":["business","small_business"],"states":["National"],"amount_display":"Varies by state STEP program"}
    },
    {
        "source": "USDA",
        "source_id": "usda-value-added-producer-grants-2026",
        "title": "USDA Value-Added Producer Grants",
        "description": "Funding for agricultural producers and food businesses developing value-added products, processing, marketing, feasibility studies, and business growth.",
        "eligibility": "Agricultural producers and eligible producer groups; verify current notice and eligibility on USDA Rural Development.",
        "audience": "organization", "category": "rural", "amount_min": None, "amount_max": 250000,
        "deadline": "Annual/seasonal; verify current cycle", "state": "National", "application_url": "https://www.rd.usda.gov/programs-services/business-programs/value-added-producer-grants",
        "verified": True, "confidence_score": 92,
        "raw_json": {"status":"Active","funding_type":"federal_grant","source_kind":"rural_business","industries":["agriculture","food","producer","farm","rural","manufacturing"],"needs_supported":["equipment","marketing","product development","working capital","business growth"],"organization_types":["business","producer","cooperative"],"states":["National"],"amount_display":"Planning/working capital grants; verify current maximum"}
    },
    {
        "source": "EPA",
        "source_id": "epa-small-business-innovation-2026",
        "title": "EPA Small Business Innovation Research Funding",
        "description": "Funding pathway for small businesses developing environmental, climate, clean energy, water, air quality, waste, and sustainability technologies.",
        "eligibility": "Eligible small businesses developing environmental technology solutions; verify current solicitations on EPA SBIR pages.",
        "audience": "organization", "category": "startup", "amount_min": None, "amount_max": None,
        "deadline": "Varies by solicitation", "state": "National", "application_url": "https://www.epa.gov/sbir",
        "verified": True, "confidence_score": 90,
        "raw_json": {"status":"Active","funding_type":"federal_innovation","source_kind":"agency_program","industries":["clean_energy","technology","manufacturing","water","climate","environment","sustainability"],"needs_supported":["research","prototype","commercialization","technology development"],"organization_types":["startup","small_business"],"states":["National"],"amount_display":"Varies by solicitation"}
    },
    {
        "source": "Comcast RISE",
        "source_id": "comcast-rise-business-support-2026",
        "title": "Comcast RISE Small Business Support",
        "description": "Small business support program that has included grants, marketing, technology, consulting, and media support for eligible businesses in selected markets.",
        "eligibility": "Eligibility and cities vary by cycle; verify current open markets and rules on Comcast RISE.",
        "audience": "organization", "category": "business", "amount_min": None, "amount_max": None,
        "deadline": "Seasonal/varies by market", "state": "National", "application_url": "https://www.comcastrise.com",
        "verified": True, "confidence_score": 88,
        "raw_json": {"status":"Active/seasonal","funding_type":"corporate_private","source_kind":"small_business_support","industries":["beauty","restaurant","retail_ecommerce","professional_services","fitness_wellness","local_business","small_business"],"needs_supported":["marketing","technology","business growth","equipment","operations"],"organization_types":["business","small_business"],"states":["National"],"amount_display":"Varies by cycle"}
    }
]
CURATED_VERIFIED_GRANTS.extend(ADDITIONAL_UNIVERSAL_FUNDING_SOURCES)

