"""Proposal generation stabilization and cleanup.

Prevents raw memory dumps, JSON/Python dicts, and platform/system wording from
leaking into client-facing proposals.
"""
from __future__ import annotations

import re

SECTION_ORDER = [
    "Executive Summary",
    "Applicant Overview",
    "Statement of Need / Problem Description",
    "Proposed Project / Program Description",
    "Goals, Objectives, and Measurable Outcomes",
    "Use of Funds",
    "Budget Narrative",
    "Sustainability Plan",
    "Evaluation and Reporting Plan",
    "Organizational Strength and Grant Fit",
    "Required Attachments Checklist",
    "Final Review Checklist",
    "Closing Statement",
]

BANNED_PATTERNS = [
    r"Prepared by\s+Grant\s+Simone",
    r"Prepared by\s+Mogul\s+Grant\s+System",
    r"Generated by[^\n]*",
    r"\bAI provider\b[^\n]*",
    r"\bMemory\b\s*",
    r"\bBudget draft\b\s*",
    r"\{[^{}]*(requested_amount_estimate|categories|note|Object|object)[^{}]*\}",
    r"\[[^\]]*(requested_amount_estimate|categories|Object|object)[^\]]*\]",
    r"\[object Object\]",
    r"Client review required before official submission",
    r"Confidential Application Draft",
]


def sanitize_proposal_text(text: str) -> str:
    cleaned = text or ""
    for pattern in BANNED_PATTERNS:
        cleaned = re.sub(pattern, " ", cleaned, flags=re.I | re.S)
    cleaned = re.sub(r"\n{3,}", "\n\n", cleaned)
    cleaned = re.sub(r"[ \t]{2,}", " ", cleaned)
    return cleaned.strip()


def stabilize_sections(text: str) -> str:
    cleaned = sanitize_proposal_text(text)
    if not cleaned:
        return cleaned
    has_sections = sum(1 for s in SECTION_ORDER if s.lower() in cleaned.lower()) >= 4
    return cleaned if has_sections else cleaned


def is_submission_safe(text: str) -> bool:
    lower = (text or "").lower()
    unsafe = [
        "prepared by grant simone",
        "prepared by mogul",
        "memory",
        "budget draft",
        "[object object]",
        "ai provider",
    ]
    return not any(x in lower for x in unsafe)
