
const api='/api';let token=localStorage.getItem('token')||'';let profiles=[];let currentUser=null;const $=id=>document.getElementById(id);

const US_STATE_OPTIONS = [
 ["", "All USA / National"],
 ["Alabama", "Alabama"], ["Alaska", "Alaska"], ["Arizona", "Arizona"], ["Arkansas", "Arkansas"],
 ["California", "California"], ["Colorado", "Colorado"], ["Connecticut", "Connecticut"], ["Delaware", "Delaware"],
 ["District of Columbia", "District of Columbia"], ["Florida", "Florida"], ["Georgia", "Georgia"], ["Hawaii", "Hawaii"],
 ["Idaho", "Idaho"], ["Illinois", "Illinois"], ["Indiana", "Indiana"], ["Iowa", "Iowa"], ["Kansas", "Kansas"],
 ["Kentucky", "Kentucky"], ["Louisiana", "Louisiana"], ["Maine", "Maine"], ["Maryland", "Maryland"],
 ["Massachusetts", "Massachusetts"], ["Michigan", "Michigan"], ["Minnesota", "Minnesota"], ["Mississippi", "Mississippi"],
 ["Missouri", "Missouri"], ["Montana", "Montana"], ["Nebraska", "Nebraska"], ["Nevada", "Nevada"],
 ["New Hampshire", "New Hampshire"], ["New Jersey", "New Jersey"], ["New Mexico", "New Mexico"], ["New York", "New York"],
 ["North Carolina", "North Carolina"], ["North Dakota", "North Dakota"], ["Ohio", "Ohio"], ["Oklahoma", "Oklahoma"],
 ["Oregon", "Oregon"], ["Pennsylvania", "Pennsylvania"], ["Rhode Island", "Rhode Island"],
 ["South Carolina", "South Carolina"], ["South Dakota", "South Dakota"], ["Tennessee", "Tennessee"], ["Texas", "Texas"],
 ["Utah", "Utah"], ["Vermont", "Vermont"], ["Virginia", "Virginia"], ["Washington", "Washington"],
 ["West Virginia", "West Virginia"], ["Wisconsin", "Wisconsin"], ["Wyoming", "Wyoming"],
 ["Puerto Rico", "Puerto Rico"], ["Guam", "Guam"], ["U.S. Virgin Islands", "U.S. Virgin Islands"],
 ["American Samoa", "American Samoa"], ["Northern Mariana Islands", "Northern Mariana Islands"]
];
function populateStateDropdowns(){
 document.querySelectorAll('[data-state-select]').forEach(sel=>{
 const mode = sel.getAttribute('data-state-select');
 const first = mode === 'profile' ? ['','Select state / territory'] : ['','All USA / National'];
 const options = [first, ...US_STATE_OPTIONS.slice(1)];
 sel.innerHTML = options.map(([value,label])=>`<option value="${esc(value)}">${esc(label)}</option>`).join('');
 });
}

function toast(msg){$('toast').textContent=msg;$('toast').classList.remove('hidden');setTimeout(()=>$('toast').classList.add('hidden'),2600)}
function msg(text,err=false){$('authMessage').textContent=text;$('authMessage').className='msg'+(err?' error':'')}
function clearMsg(){$('authMessage').className='msg hidden';$('authMessage').textContent=''}
const PLAN_LABELS={individual_elite:'Individual Elite - $99/mo',business_owner:'Business Owner - $299/mo',white_label_platform:'White Label Platform - $5,000/yr',individual_starter:'Individual Elite - $99/mo',individual_pro:'Individual Elite - $99/mo',business_growth:'Business Owner - $299/mo',business_scale:'Business Owner - $299/mo',business_enterprise:'Business Owner - $299/mo',white_label_agency:'White Label Platform - $5,000/yr',white_label_studio:'White Label Platform - $5,000/yr',white_label:'White Label Platform - $5,000/yr'};
const FEATURE_LABELS={grant_search:'Grant Discovery',proposals:'Applications / Proposals',workflows:'AI Workflows',documents:'Document Vault',pdf_exports:'PDF Exports',private_grants:'Private/Corporate Grants',white_label:'White Label',admin:'Admin Controls',notifications:'Notifications',tracker:'Tracker',profiles:'Funding Profiles',client_profile:'Client Profile'};
const PAGE_FEATURE={grants:'grant_search',proposals:'proposals',workflows:'workflows',documents:'documents',white:'white_label',admin:'admin',notifications:'notifications',apps:'tracker',profiles:'profiles',client:'client_profile'};
function showLogin(){clearMsg();$('loginPanel').classList.remove('hidden');$('signupPanel').classList.add('hidden');$('loginTab').classList.add('active');$('signupTab').classList.remove('active')}
function showSignup(){clearMsg();$('signupPanel').classList.remove('hidden');$('loginPanel').classList.add('hidden');$('signupTab').classList.add('active');$('loginTab').classList.remove('active');if(!$('signupPlan').value){$('signupButton').disabled=true;$('signupButton').textContent='Choose a Plan First';if($('selectedPlanBanner')){$('selectedPlanBanner').classList.remove('hidden');$('selectedPlanBanner').innerHTML='<strong>No plan selected.</strong><br><span class="mini">Please choose a plan from the pricing page before creating an account.</span><br><br><a class="btn secondary" href="/index.html#plans">Back to Plans</a>'}}}
function pickPlan(plan){location.href='/signup.html?plan='+encodeURIComponent(plan)}
function applySelectedPlan(plan){if(!plan||!PLAN_LABELS[plan]){if($('selectedPlanHero'))$('selectedPlanHero').innerHTML='<strong>No plan selected.</strong><br><span class="mini">Choose a plan on the pricing page to create your account.</span><br><br><a class="btn secondary" href="/index.html#plans">Back to Plans</a>';return}if($('signupPlan'))$('signupPlan').value=plan;if(plan.startsWith('business_')){$('accountType').value='business'}else if(plan.startsWith('white_label')){$('accountType').value='agency'}else{$('accountType').value='individual'}const label=PLAN_LABELS[plan];$('signupButton').disabled=false;$('signupButton').textContent='Create Account';if($('selectedPlanBanner')){$('selectedPlanBanner').classList.remove('hidden');$('selectedPlanBanner').innerHTML='<strong>Selected Plan:</strong> '+label+'<br><span class="mini">Your selected plan controls feature access. You can start after account creation.</span><br><br><a href="/index.html#plans">Change plan</a>'}if($('selectedPlanHero')){$('selectedPlanHero').innerHTML='<strong>Your selected plan:</strong> '+label+'<br><span class="mini">Create your account and start using Mogul Grant System.</span>'}}
function headers(){return {'Content-Type':'application/json','Authorization':'Bearer '+token}}
async function request(path,opts={}){const r=await fetch(api+path,{...opts,headers:{...headers(),...(opts.headers||{})}});let t=await r.text();let d={};try{d=t?JSON.parse(t):{}}catch(e){d={detail:t}}if(!r.ok){let detail=d.detail||t||'Request failed';if(Array.isArray(detail)){detail=detail.map(x=>x.msg||JSON.stringify(x)).join("\n")}throw new Error(detail)}return d}
async function enter(){document.title='Mogul Grant System Dashboard';if(location.pathname.includes('signup.html')||location.pathname==='/dashboard'){history.replaceState({},'', '/signup.html')}$('authShell').classList.add('hidden');$('app').classList.remove('hidden');await loadMe();loadProfiles();loadNotifications()}
function clearSession(){localStorage.removeItem('token');localStorage.removeItem('access_token');localStorage.removeItem('user');sessionStorage.clear();token='';currentUser=null;profiles=[]}
async function register(){try{clearSession();clearMsg();if(!$('signupPlan').value){msg('Please choose a plan from the pricing page first.',true);return}const password=$('signupPassword').value;if(password.length<8){msg('Password must be at least 8 characters.',true);return}if(!$('signupEmail').value.trim()){msg('Please enter your email address.',true);return}document.body.classList.add('loading');const workspaceName=$('tenantNameSignup').value.trim()||(($('signupName').value.trim()||'Mogul Grant System')+' Workspace');const body={email:$('signupEmail').value.trim(),password:password,full_name:$('signupName').value.trim()||'Member',tenant_slug:'default',tenant_name:workspaceName,account_type:$('accountType').value,plan:$('signupPlan').value};const d=await request('/auth/register',{method:'POST',body:JSON.stringify(body)});token=d.access_token;localStorage.setItem('token',token);if(d.payment_required && d.checkout_url){msg('Account created. Redirecting to secure checkout...');window.location.href=d.checkout_url}else{msg('Account created. You now have access.');toast('Welcome to Mogul Grant System.');enter()}}catch(e){msg(e.message,true)}finally{document.body.classList.remove('loading')}}
async function login(){try{clearSession();clearMsg();if(!$('loginEmail').value.trim()||!$('loginPassword').value){msg('Enter your email and password.',true);return}document.body.classList.add('loading');const body={email:$('loginEmail').value.trim(),password:$('loginPassword').value,tenant_slug:'default'};const d=await request('/auth/login',{method:'POST',body:JSON.stringify(body)});token=d.access_token;localStorage.setItem('token',token);enter();toast('Logged in')}catch(e){msg(e.message,true)}finally{document.body.classList.remove('loading')}}
function activeFeatures(){return (currentUser&&currentUser.features)||{}}
function featureAllowed(feature){if(!feature)return true;return !!activeFeatures()[feature]}
function formatLimit(v){return Number(v)>=999999?'Unlimited':esc(v??0)}
function renderUsage(u){if(!$('usageSummary'))return;const limits=(u&&u.limits)||{};const used=(u&&u.used)||{};const credits=(u&&u.credits)||{};const keys=[['grant_searches','Grant searches'],['proposals','Proposals'],['workflows','Workflows'],['documents','Documents'],['pdf_exports','PDF exports']];const creditTotal=Number(credits.total||0);const creditUsed=Number(credits.used||0);const creditRemaining=creditTotal>=999999?'Unlimited':Number(credits.remaining||0);let html='';if(activePreviewPlan){html+=`<div class="preview-banner"><strong>Preview mode:</strong> ${esc(PLAN_LABELS[activePreviewPlan]||activePreviewPlan)}<br><span class="mini">You are viewing the app as this plan. Your admin account is unchanged.</span><br><br><button type="button" class="btn secondary" onclick="exitPreviewMode()">Exit Preview Mode</button></div>`}html+=`<div class="usage-card"><span class="mini">Monthly credits</span><strong>${creditUsed} used</strong><div class="progress"><span style="width:${creditTotal>0&&creditTotal<999999?Math.min(100,Math.round((creditUsed/creditTotal)*100)):0}%"></span></div><p class="mini">Remaining: ${creditRemaining} • Resets: ${esc(credits.reset_date||'monthly')}</p></div>`;html+=keys.map(([k,label])=>{const lim=Number(limits[k]||0);const val=Number(used[k]||0);const pct=lim>0&&lim<999999?Math.min(100,Math.round((val/lim)*100)):0;return `<div class="usage-card"><span class="mini">${label}</span><strong>${val} / ${formatLimit(lim)}</strong><div class="progress"><span style="width:${pct}%"></span></div></div>`}).join('');html+=`<div class="usage-card"><span class="mini">Current plan</span><strong>${esc(PLAN_LABELS[u?.plan]||u?.label||u?.plan||'Plan')}</strong></div>`;$('usageSummary').innerHTML=html}
function applyPlanUI(){const features=activeFeatures();document.querySelectorAll('.nav button[data-page]').forEach(btn=>{const page=btn.dataset.page;const f=PAGE_FEATURE[page];const allowed=!f||features[f];btn.classList.toggle('hidden',!allowed);btn.classList.toggle('locked',!!f&&!allowed);});if($('adminNav'))$('adminNav').classList.toggle('hidden',!features.admin && !activePreviewPlan);if($('whiteNav'))$('whiteNav').classList.toggle('hidden',!features.white_label)}
async function loadMe(){try{currentUser=await request('/auth/me');realFeatures={...(currentUser.features||{})};renderUsage(currentUser.usage||{});applyPlanUI()}catch(e){console.warn(e.message)}}
function exitPreviewMode(){activePreviewPlan=null;if(currentUser&&realFeatures){currentUser.features={...realFeatures}}renderUsage(currentUser.usage||{});applyPlanUI();toast('Preview mode closed')}
function logout(){clearSession();window.location.replace('/signup.html?mode=login&logged_out=1')}
function showUpgrade(feature){const label=FEATURE_LABELS[feature]||'This feature';toast(label+' is not included in your current plan.');showPage('dashboard',navButton('dashboard'))}
function showPage(id,btn){const feature=PAGE_FEATURE[id];if(feature&&!featureAllowed(feature)){showUpgrade(feature);return}document.querySelectorAll('.page').forEach(p=>p.classList.add('hidden'));$(id).classList.remove('hidden');document.querySelectorAll('.nav button').forEach(b=>b.classList.remove('active'));if(btn)btn.classList.add('active');if(id==='client')loadClientProfile();if(id==='profiles')loadProfiles();if(id==='grants')loadProfiles();if(id==='proposals')loadProfiles().then(loadProposals);if(id==='workflows')loadProfiles().then(loadWorkflows).then(loadAgentRuns);if(id==='apps')loadApps();if(id==='documents')loadDocuments();if(id==='admin')loadAdmin();if(id==='notifications'){loadNotifications();loadNotificationSettings()}}
function navButton(page){return document.querySelector('.nav button[data-page="'+page+'"]')}
function dashboardGo(type){if(type==='subscriptions'){window.location.href='/index.html#plans';return}showPage('profiles',navButton('profiles'));if(type==='individual'){$('profileType').value='individual';$('profileName').focus()}else{$('profileType').value='business';$('profileName').focus()}}

async function loadClientProfile(){try{const d=await request('/auth/client-profile');const user=d.user||{};const tenant=d.tenant||{};const sub=d.subscription||{};const usage=d.usage||{};const features=d.features||{};const info=(obj)=>Object.entries(obj).map(([k,v])=>`<div class="info-row"><span>${esc(k.replaceAll('_',' '))}</span><strong>${esc(v??'')}</strong></div>`).join('');$('clientAccount').innerHTML=info({name:user.full_name,email:user.email,role:user.role,account_type:user.account_type,email_verified:user.email_verified?'Yes':'No'});$('clientPlan').innerHTML=info({plan:PLAN_LABELS[d.plan]||d.plan,status:sub.status||'active/trial',payment_status:user.payment_status||'trialing'});$('clientWorkspace').innerHTML=info({workspace:tenant.name,slug:tenant.slug,domain:tenant.domain||'Not set',audience:tenant.audience_mode||'all'});$('clientFeatures').innerHTML=Object.keys(FEATURE_LABELS).filter(k=>k!=='admin').map(k=>`<div class="usage-card ${features[k]?'':'locked'}"><span class="mini">${FEATURE_LABELS[k]}</span><strong>${features[k]?'Included':'Locked'}</strong></div>`).join('');$('clientProfiles').innerHTML=(d.profiles||[]).map(o=>`<div class="item"><span class="pill">${esc(o.profile_type||o.org_type||'profile')}</span><h3>${esc(o.name)}</h3><p>${esc(o.city||'')} ${esc(o.state||'')}</p><p>${esc(o.funding_goals||o.mission||'')}</p></div>`).join('')||'<p class="muted">No funding profiles yet.</p>'}catch(e){toast(e.message)}}
async function createProfile(){const pt=$('profileType').value;const body={name:$('profileName').value||'My Funding Profile',profile_type:pt,org_type:pt,state:$('profileState').value,city:$('profileCity').value,annual_income:$('profileIncome').value?Number($('profileIncome').value):null,annual_budget:$('profileIncome').value?Number($('profileIncome').value):null,education_level:$('profileEducation').value,mission:$('profileGoals').value,funding_goals:$('profileGoals').value,veteran_status:$('veteranStatus').checked,disability_status:$('disabilityStatus').checked,eligibility_tags:[pt,$('profileEducation').value].filter(Boolean)};await request('/organizations',{method:'POST',body:JSON.stringify(body)});toast('Funding profile created');loadProfiles()}
async function loadProfiles(){profiles=await request('/organizations');$('profileList').innerHTML=profiles.map(o=>`<div class="item"><span class="pill">${esc(o.profile_type||o.org_type||'profile')}</span><h3>${esc(o.name)}</h3><p>${esc(o.city||'')} ${esc(o.state||'')}</p><p>${esc(o.funding_goals||o.mission||'')}</p></div>`).join('')||'<p class="muted">No funding profiles yet.</p>';const opts=profiles.map(o=>`<option value="${o.id}">${esc(o.name)} - ${esc(o.profile_type||o.org_type)}</option>`).join('');$('grantProfile').innerHTML='<option value="">No profile selected</option>'+opts;$('proposalProfile').innerHTML=opts||'<option value="">Create a funding profile first</option>';$('workflowProfile').innerHTML=opts||'<option value="">Create a funding profile first</option>';if($('documentProfile'))$('documentProfile').innerHTML='<option value="">General documents</option>'+opts}
async function searchGrants(){try{$('grantResults').innerHTML='<p class=\"muted\">Searching verified grants only...</p>';const body={query:$('grantQuery').value||'funding assistance',state:$('grantState').value||null,organization_id:$('grantProfile').value?Number($('grantProfile').value):null,audience:$('grantAudience').value,category:$('grantCategory').value,limit:12};const d=await request('/grants/search',{method:'POST',body:JSON.stringify(body)});const grants=d.grants||[];if(!grants.length){$('grantResults').innerHTML=`<div class=\"item\"><h3>No verified relevant grants found yet</h3><p>${esc(d.message||'No matching verified grants were found for this state and need. No dummy grants are shown.')}</p><p class=\"muted\">Tip: broaden the need, select All USA, or add/run verified sources for that state. No dummy grants are shown.</p></div>`;return;}$('grantResults').innerHTML=grants.map(g=>`<div class=\"item\"><span class=\"pill\">ID ${g.id} • ${esc(g.audience)} • Match ${Math.round(g.match_score||g.confidence_score||0)}%</span><h3>${esc(g.title)}</h3><p>${esc(g.description)}</p><p class=\"muted\">Category: ${esc(g.category||'')} • State: ${esc(g.state||'National')} • Source: ${esc(g.source)} • Deadline: ${esc(g.deadline||'Varies')}</p><div class=\"actions\"><a class=\"btn secondary\" href=\"${g.application_url||'#'}\" target=\"_blank\">Official Link</a><button type=\"button\" class=\"btn secondary\" onclick=\"useGrant(${Number(g.id)||0})\">Use This Grant</button></div></div>`).join('')}catch(e){$('grantResults').innerHTML='<p class=\"muted\">Search error: '+esc(e.message)+'</p>'}}
function useGrant(id){if(!id)return;$('proposalGrantId').value=id;$('workflowGrantId').value=id;showPage('proposals',navButton('proposals'));toast('Grant ID '+id+' selected for proposal')}
async function generateProposal(){try{if(!featureAllowed('proposals'))return showUpgrade('proposals');if(!$('proposalProfile').value){toast('Create or select a funding profile first.');showPage('profiles',navButton('profiles'));return}const d=await request('/proposals/generate',{method:'POST',body:JSON.stringify({organization_id:Number($('proposalProfile').value),grant_id:$('proposalGrantId').value?Number($('proposalGrantId').value):null,requested_amount:$('amount').value?Number($('amount').value):null,funding_purpose:$('purpose').value})});toast('Application narrative generated. Score '+Math.round(d.score||0));loadProposals()}catch(e){toast(e.message)}}
async function downloadProposal(id){try{const res=await fetch(api+'/proposals/'+id+'/pdf',{headers:{Authorization:'Bearer '+token}});if(!res.ok){let msg='PDF download failed';try{const j=await res.json();msg=j.detail||msg}catch(_){ }throw new Error(msg)}const blob=await res.blob();const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='application-narrative-'+id+'.pdf';document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(url);toast('PDF downloaded')}catch(e){toast(e.message)}}
async function loadProposals(){const arr=await request('/proposals');$('proposalList').innerHTML=(arr||[]).map(p=>`<div class=\"item\"><span class=\"pill\">Score ${Math.round(p.score||0)}</span><h3>${esc(p.title)}</h3><p class=\"muted\">${esc(p.created_at||'')}</p><button type=\"button\" class=\"btn secondary\" onclick=\"downloadProposal(${p.id})\">Download PDF</button></div>`).join('')||'<p class=\"muted\">No application narratives yet.</p>'}
async function startWorkflow(){try{if(!featureAllowed('workflows'))return showUpgrade('workflows');if(!$('workflowProfile').value){toast('Create or select a funding profile first.');showPage('profiles',navButton('profiles'));return}const payload={workflow:'full_grant_pipeline',organization_id:Number($('workflowProfile').value)}; if($('workflowGrantId').value){payload.grant_id=Number($('workflowGrantId').value)} const d=await request('/workflows/start',{method:'POST',body:JSON.stringify(payload)});$('workflowOut').innerHTML='<div class="item"><h3>AI workflow started</h3><p>The agents are running. Grant Hunter will select a verified grant if Grant ID is blank.</p><p class="muted">Workflow ID: '+esc(d.workflow_run_id||d.id||'created')+'</p></div>';toast('AI agents started.');setTimeout(loadWorkflows,2500);setTimeout(loadAgentRuns,3500)}catch(e){$('workflowOut').innerHTML='<p class="muted">'+esc(e.message)+'</p>'}}
async function loadWorkflows(){const runs=await request('/workflows');const arr=Array.isArray(runs)?runs:(runs.workflows||[]);$('workflowOut').innerHTML=arr.length?arr.slice(0,10).map(renderWorkflowCard).join(''):'<p class="muted">No workflow runs yet.</p>';loadAgentRuns()}
async function loadAgentRuns(){try{const rows=await request('/agents/runs');$('agentRuns').innerHTML=rows.slice(0,30).map(a=>`<div class="item"><span class="pill">${esc(a.agent_name)} • ${esc(a.status)}</span>${renderAgentOutput(a.output_json||{})}</div>`).join('')||'<p class="muted">No agent activity yet.</p>'}catch(e){$('agentRuns').innerHTML='<p class="muted">Agent activity will appear after a workflow runs.</p>'}}
async function loadApps(){const arr=await request('/applications');$('appList').innerHTML=(arr||[]).map(a=>`<div class="item"><span class="pill">${esc(a.status)}</span><h3>Application #${a.id}</h3><p>Grant ID ${a.grant_id} • Proposal ${a.proposal_id||''}</p><div class="actions"><button type="button" class="btn secondary" onclick="approveApp(${a.id})">Approve</button><button type="button" class="btn" onclick="submitApp(${a.id})">Mark Submitted</button></div></div>`).join('')||'<p class="muted">No tracked applications yet.</p>'}
async function approveApp(id){await request('/applications/'+id+'/approve',{method:'POST'});toast('Application approved');loadApps()}
async function submitApp(id){await request('/applications/'+id+'/mark-submitted',{method:'POST'});toast('Application marked submitted');loadApps()}

async function uploadDocument(){try{if(!featureAllowed('documents'))return showUpgrade('documents');const f=$('documentFile').files[0];if(!f){toast('Choose a file first');return}const fd=new FormData();fd.append('file',f);if($('documentProfile').value)fd.append('organization_id',$('documentProfile').value);fd.append('document_type',$('documentType').value||'supporting_document');const r=await fetch(api+'/documents',{method:'POST',headers:{Authorization:'Bearer '+token},body:fd});const text=await r.text();let d={};try{d=text?JSON.parse(text):{}}catch(_){d={detail:text}}if(!r.ok)throw new Error(d.detail||text||'Upload failed');toast('Document uploaded');$('documentFile').value='';loadDocuments();loadMe()}catch(e){toast(e.message)}}
async function loadDocuments(){try{const arr=await request('/documents');$('documentList').innerHTML=(arr||[]).map(d=>`<div class="item"><span class="pill">${esc(d.document_type)} • ${Math.round((d.size_bytes||0)/1024)} KB</span><h3>${esc(d.original_filename)}</h3><p>${esc(d.content_type||'file')}</p><a class="btn secondary" href="${api}/documents/${d.id}/download" target="_blank" onclick="event.preventDefault();downloadDocument(${d.id},'${esc(d.original_filename)}')">Download</a></div>`).join('')||'<p class="muted">No documents uploaded yet.</p>'}catch(e){$('documentList').innerHTML='<p class="muted">'+esc(e.message)+'</p>'}}
async function downloadDocument(id,name){try{const res=await fetch(api+'/documents/'+id+'/download',{headers:{Authorization:'Bearer '+token}});if(!res.ok)throw new Error('Download failed');const blob=await res.blob();const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=name||'document';document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(url)}catch(e){toast(e.message)}}

async function loadNotifications(){try{const d=await request('/notifications');const unread=d.unread||0;$('notifBadge').textContent=unread;$('notifBadge').classList.toggle('hidden',!unread);$('notificationList').innerHTML=(d.notifications||[]).map(n=>`<div class="item"><span class="pill">${esc(n.type)} • ${n.is_read?'Read':'Unread'} • ${esc(n.priority)}</span><h3>${esc(n.title)}</h3><p>${esc(n.message)}</p><div class="actions">${n.action_url?`<a class="btn secondary" href="${esc(n.action_url)}" target="_blank">Official Link</a>`:''}<button type="button" class="btn" onclick="markNotificationRead(${n.id})">Mark Read</button></div></div>`).join('')||'<p class="muted">No notifications yet. Create a profile, then scan for matches.</p>'}catch(e){if($('notificationList'))$('notificationList').innerHTML='<p class="muted">'+esc(e.message)+'</p>'}}
async function markNotificationRead(id){await request('/notifications/'+id+'/read',{method:'POST'});loadNotifications()}
async function scanNotifications(){const d=await request('/notifications/scan-now',{method:'POST'});toast('Created '+(d.created_notifications||0)+' new grant alerts');loadNotifications()}
async function loadNotificationSettings(){try{const s=await request('/notifications/settings');$('emailGrantMatches').checked=!!s.email_grant_matches;$('platformGrantMatches').checked=!!s.platform_grant_matches;$('minimumMatchScore').value=s.minimum_match_score||75}catch(e){}}
async function saveNotificationSettings(){await request('/notifications/settings',{method:'PATCH',body:JSON.stringify({email_grant_matches:$('emailGrantMatches').checked,platform_grant_matches:$('platformGrantMatches').checked,email_deadline_reminders:true,minimum_match_score:Number($('minimumMatchScore').value||75),categories_json:[],states_json:[]})});toast('Notification settings saved')}

function renderKeyValues(obj){return '<div class="kv-grid">'+Object.entries(obj||{}).map(([k,v])=>`<div class="kv"><span>${esc(k.replaceAll('_',' '))}</span><strong>${esc(v===true?'Yes':v===false?'No':v??'')}</strong></div>`).join('')+'</div>'}
function renderAdminDashboard(d){const counts={tenants:d.tenants,users:d.users,grants:d.grants,proposals:d.proposals,applications:d.applications,workflows:d.workflows,agent_runs:d.agent_runs,documents:d.documents,usage_events:d.usage_events,audit_logs:d.audit_logs};let html='<h3>Platform Overview</h3>'+renderKeyValues(counts);if(d.current_user_usage){const u=d.current_user_usage;html+=`<h3 style="margin-top:18px">Current Admin Plan</h3>`+renderKeyValues({plan:u.label||u.plan,credits_remaining:u.credits?.remaining>=999999?'Unlimited':u.credits?.remaining,grant_searches_used:u.used?.grant_searches||0,proposals_used:u.used?.proposals||0,workflows_used:u.used?.workflows||0,reset_date:u.credits?.reset_date||'monthly'});}return html}
function renderWorkflowCard(w){return `<div class="item"><span class="pill">${esc(w.status||'workflow')} • ${esc(w.workflow||'funding pipeline')}</span><h3>Workflow #${esc(w.id||'')}</h3><p>Profile ID: ${esc(w.organization_id||'')} • Grant ID: ${esc(w.grant_id||'Auto-selected')}</p><p class="muted">Started: ${esc(w.created_at||'')}</p></div>`}
function renderAgentOutput(output){if(!output||typeof output!=='object')return esc(output||'No details yet.');const parts=[];for(const [k,v] of Object.entries(output)){if(Array.isArray(v))parts.push(`<div><strong>${esc(k.replaceAll('_',' '))}:</strong> ${esc(v.slice(0,4).join(', '))}</div>`);else if(typeof v==='object'&&v)parts.push(`<div><strong>${esc(k.replaceAll('_',' '))}:</strong> ready</div>`);else parts.push(`<div><strong>${esc(k.replaceAll('_',' '))}:</strong> ${esc(v)}</div>`)}return '<div class="check-list">'+parts.slice(0,8).join('')+'</div>'}
function renderTenantSaved(d){return '<h3>Branding saved</h3>'+renderKeyValues({name:d.name,domain:d.domain||'Not set',primary_color:d.primary_color,background_color:d.background_color,audience_mode:d.audience_mode})}
function renderPreviewDetails(plan,features,matrix){let html=`<div class="preview-banner"><strong>Viewing as:</strong> ${esc(PLAN_LABELS[plan]||plan)}<br><span class="mini">Sidebar/features now reflect this plan. This does not change your real admin account.</span><br><br><button type="button" class="btn secondary" onclick="exitPreviewMode()">Exit Preview Mode</button></div>`;const m=(matrix&&matrix[0])||{};html+='<h3>Plan Limits</h3>'+renderKeyValues({price:m.price||'',credits:m.credits>=999999?'Unlimited':m.credits,grant_searches:m.grant_searches>=999999?'Unlimited':m.grant_searches,proposals:m.proposals>=999999?'Unlimited':m.proposals,workflows:m.workflows>=999999?'Unlimited':m.workflows,documents:m.documents>=999999?'Unlimited':m.documents,pdf_exports:m.pdf_exports>=999999?'Unlimited':m.pdf_exports});html+='<h3>Feature Access</h3><div class="usage-grid">'+Object.keys(FEATURE_LABELS).map(k=>`<div class="usage-card ${features[k]?'':'locked'}"><span class="mini">${FEATURE_LABELS[k]}</span><strong>${features[k]?'Included':'Locked'}</strong></div>`).join('')+'</div>';return html}

async function saveTenant(){if(!featureAllowed('white_label'))return showUpgrade('white_label');const d=await request('/tenants/current',{method:'PATCH',body:JSON.stringify({name:$('tenantName').value,domain:$('tenantDomain').value,primary_color:$('primaryColor').value,background_color:$('bgColor').value,audience_mode:$('audienceMode').value})});$('tenantOut').innerHTML=renderTenantSaved(d);toast('Branding saved')}
async function loadAdmin(){try{const d=await request('/admin/dashboard');$('adminOut').innerHTML=renderAdminDashboard(d);loadPlanMatrix()}catch(e){$('adminOut').innerHTML='<p class="muted">'+esc(e.message)+'</p>'}}
async function loadPlanMatrix(){try{const d=await request('/admin/plans');const plans=d.plans||[];$('adminPlanMatrix').innerHTML=plans.map(p=>`<div class="item"><span class="pill">${esc(p.label)} • ${esc(p.price||'')}</span><h3>${esc(p.label)}</h3><p>Credits/month: <strong>${p.credits>=999999?'Unlimited':p.credits}</strong></p><p>Searches: ${p.grant_searches>=999999?'Unlimited':p.grant_searches} • Proposals: ${p.proposals>=999999?'Unlimited':p.proposals} • Workflows: ${p.workflows>=999999?'Unlimited':p.workflows}</p><p>PDF exports: ${p.pdf_exports>=999999?'Unlimited':p.pdf_exports} • Documents: ${p.documents>=999999?'Unlimited':p.documents} • Team: ${p.team_members>=999999?'Unlimited':p.team_members}</p><p>Private grants: ${p.private_grants?'Yes':'No'} • White label: ${p.white_label?'Yes':'No'} • Admin: ${p.admin_access?'Yes':'No'}</p><button type="button" class="btn secondary" onclick="previewPlan('${p.plan}')">View as this plan</button></div>`).join('')||'<p class="muted">No plans available.</p>'}catch(e){$('adminPlanMatrix').innerHTML='<p class="muted">'+esc(e.message)+'</p>'}}
async function previewPlan(plan){try{const d=await request('/admin/preview/'+plan);activePreviewPlan=plan;if(currentUser){currentUser.features=d.features||currentUser.features}applyPlanUI();renderUsage(currentUser?.usage||{});$('adminOut').innerHTML=renderPreviewDetails(plan,d.features||{},d.matrix||[]);showPage('dashboard',navButton('dashboard'));toast('Preview mode active: '+(PLAN_LABELS[plan]||plan))}catch(e){toast(e.message)}}
function esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;'}[c]))}
populateStateDropdowns();
$('loginTab').onclick=showLogin;$('signupTab').onclick=showSignup;$('switchToSignup').onclick=showSignup;$('switchToLogin').onclick=showLogin;$('loginButton').onclick=login;$('signupButton').onclick=register;$('logoutButton').onclick=logout;$('createProfileButton').onclick=createProfile;$('searchGrantsButton').onclick=searchGrants;$('generateProposalButton').onclick=generateProposal;$('startWorkflowButton').onclick=startWorkflow;$('loadAppsButton').onclick=loadApps;if($('uploadDocumentButton'))$('uploadDocumentButton').onclick=uploadDocument;$('saveTenantButton').onclick=saveTenant;$('loadAdminButton').onclick=loadAdmin;if($('loadPlanMatrixButton'))$('loadPlanMatrixButton').onclick=loadPlanMatrix;if($('loadNotificationsButton'))$('loadNotificationsButton').onclick=loadNotifications;if($('scanNotificationsButton'))$('scanNotificationsButton').onclick=scanNotifications;if($('saveNotificationSettingsButton'))$('saveNotificationSettingsButton').onclick=saveNotificationSettings;document.querySelectorAll('.nav button').forEach(btn=>btn.onclick=()=>showPage(btn.dataset.page,btn));['loginPassword','signupPassword'].forEach(id=>$(id).addEventListener('keydown',e=>{if(e.key==='Enter') id==='loginPassword'?login():register()}));const params=new URLSearchParams(location.search);const selectedPlan=params.get('plan');const mode=params.get('mode');if(selectedPlan){applySelectedPlan(selectedPlan);showSignup()}else if(mode==='signup'){applySelectedPlan(null);showSignup()}else if(mode==='login'){applySelectedPlan(null);showLogin()}else{applySelectedPlan(null)}if(params.get('payment')==='success'){toast('Payment successful. Your account is active.');history.replaceState({},'',location.pathname)}if(params.get('payment')==='cancelled'){msg('Payment was cancelled.',true);history.replaceState({},'',location.pathname)}if(token)enter();
